### ISSUE TITLE
View: See other user's approved ads during auction

### ISSUE THREAD

**Issue by wtogami** [slickage/adness#34]
In the spirit of transparency, auction participants should be able to click on other users during an active auction to see what approved ads they are bidding against.

**Comment by wtogami** [comment]
When viewing a bidder's approved ads, it would be simple to also have a link in that view to that user's previous forum posts.

https://bitcointalk.org/index.php?action=profile;u=81508;sa=showPosts
For example, here are my posts.

**Comment by taesup** [comment]
I can make the username a link that goes to the user's profile page (in the auction view). This page is publicly viewable and contains all ads (in rotation, approved, submitted, and saved). I can keep this link active even if the auction is over. (That would actually be easier)

Although I'm not quite sure what the point of showing the user's previous forum posts serves in this context.

**Comment by taesup** [comment]
fixed in commit a04366df20
