### ISSUE TITLE
Auto-replace ad defined CSS id and class names

### ISSUE THREAD

**Issue by wtogami** [slickage/adness#53]
To avoid accidental clashes with CSS id/class names of the forum or between ads, ad CSS/HTML will need to auto-replace such identifiers defined by an ad with a randomized string during rendering.

**Comment by theymos** [comment]
The forum currently creates "random" classes like this (each class gets a unique ID $i):

```
function cobfus($i) {
        $ret = strrev(dechex($_SERVER['REQUEST_TIME']+$i));
        $hex = "0123456789abcdef";
        $modify = "ghijklmnopqrstuv";
        $ret[0] = $modify[strpos($hex, $ret[0])];
        return $ret;
}
```

Using REQUEST_TIME is faster than using random data, and it makes the function immutable within the script's execution. Time is reversed so that CSS ^= can't be used. ($= isn't handled, but it could be.)

**Comment by wtogami** [comment]
https://github.com/slickage/adness/blob/master/namegenerator.js
generateRandomName() generates suitable random names while also being careful to avoid random clashes with real names.  It uses Math.random() which is weak, fast randomness.  This function is very fast, measured at 1,000 generations in less than 7 milliseconds on my Core i5 laptop.
