### ISSUE TITLE
Ad editor preview style

### ISSUE THREAD

**Issue by theymos** [slickage/adness#60]
The ad editor should contain the ad previews within a block element with style `font-size: 90%; text-align: center;`, as this is how ads are displayed on the forum.

**Comment by wtogami** [comment]
If the ad preview were to be a mockup that used the same layout and CSS as a real SMF thread, it would have two benefits:
- Customers can more easily edit their ad and see how it would look in production.
- Admins can more easily check that it meets the guidelines and doesn't mess up the layout in some way.

Related to Issue #63

**Comment by taesup** [comment]
Updated the editor to be full width to more match the forum while previewing. There really is no reason mock the CSS and layout of the forum any more than this since in the forum it's really just a full width table row that they ad is injected into.

**Comment by wtogami** [comment]
Well, that depends on what is decided for #63.  If we end up removing the wrapping then the mockup I describe would be a lot more useful.

Also the mockup for has benefits to the customer, although admittedly not very important for now.
