### ISSUE TITLE
Ads from unpaid users should not be listed in the review queue

### ISSUE THREAD

**Issue by theymos** [slickage/adness#61]
As an anti-spam measure, users who haven't paid the registration fee should either be unable to submit ads, or their ads should be hidden from the ad review queue until they've paid.

**Comment by wtogami** [comment]
Note: Admin users can do some thing without paying the registration fee, so please be sure to do testing from the user point of view. 

For customer workflow it would be a time wasting hurdle that could possibly scare away a potential new bidder if they have to wait <unknown number of Bitcoin confirmations> before they can begin to edit ads.  So ideally we want not-yet-paid users to be able to edit and submit ads, but they are not visible in the Needs Review admin page.  The not-yet-paid user should see a very obvious notice at the top of most pages with a link to their invoice.

**Comment by theymos** [comment]
I did test this with a non-Admin user.
