### ISSUE TITLE
Invalid ad wrapper ID

### ISSUE THREAD

**Issue by theymos** [slickage/adness#63]
According to the W3C validator, something like `<div id="#yfuraalz">` is invalid XHTML 1.0 Transitional because IDs apparently can't contain the # character.

Actually, the wrapper should probably be removed. Ad reviewers will check that ads have non-conflicting classes.

**Comment by wtogami** [comment]
- Document on the editor page that advertisers can use symbols REPLACE1, REPLACE2, REPLACE3 which are auto-replaced with a random ID.  It will be well within their best interests to do instead of using static ID's. #74

**Comment by taesup** [comment]
I can remove the hashtag from the id. That's incorrectly injected into the html. I vote that we keep the wrapper since it's the best way to scope the CSS and keep any ad CSS from straying from intended target.

**Comment by wtogami** [comment]
OK, removing only hashtag for now.  Split the REPLACE symbols into #74.
