### ISSUE TITLE
HTML entities should not be decoded by the ad editor

### ISSUE THREAD

**Issue by theymos** [slickage/adness#84]
If I input an HTML entity such as &#8482; into the ad editor, this is converted into an actual character before being inserted into the database. But Adness uses UTF-8(?), and the forum uses ISO-8859-1, so this almost always results in garbled characters. Entities should not be converted.

**Comment by taesup** [comment]
There's a fix for this in 20c82bba0015869839eb827ab48d532b8fc1f97a but be warned that although the initial creation of an ad using the escaped code works fine, any future update to the same ad will save the HTML code as its converted form since it is converted on being shown to the user.

**Comment by theymos** [comment]
That's likely to cause even more confusion as people edit their ads later and they become broken. Entities should never be converted.

(This sort of bug is why I've said that for epochtalk, user input should probably be stored in the database as the user entered it, and only converted upon display.)

**Comment by taesup** [comment]
Already fixed. Check previous commit.
